const nodemailer = require('nodemailer');
 
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: process.env.SMTP_PORT,
  secure: false,
  auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS }
});
 
exports.sendInvoiceEmail = async ({ to, customerName, invoiceNumber, amount, dueDate, companyName, pdfUrl }) => {
  await transporter.sendMail({
    from: process.env.SMTP_FROM,
    to,
    subject: `Invoice ${invoiceNumber} from ${companyName}`,
    html: `
      <div style='font-family:Arial,sans-serif;max-width:600px;margin:0 auto;'>
        <div style='background:#0a4f45;padding:24px;text-align:center;'>
          <h1 style='color:white;margin:0;font-size:24px;'>${companyName}</h1>
        </div>
        <div style='padding:32px;background:#f9f9f9;'>
          <p>Dear ${customerName},</p>
          <p>Please find attached your invoice <strong>${invoiceNumber}</strong>
             for the amount of <strong>₦${amount}</strong>.</p>
          <p>Payment is due by: <strong>${dueDate}</strong></p>
          <div style='margin:24px 0;padding:16px;background:#0a4f45;border-radius:8px;text-align:center;'>
            <p style='color:white;margin:0;font-size:18px;font-weight:bold;'>
              Amount Due: ₦${amount}</p>
          </div>
          <p style='color:#666;font-size:14px;'>
            This invoice was generated by AccounTrack™ Pro.</p>
        </div>
      </div>`
  });
};
exports.sendPasswordResetEmail = async ({ to, token, firstName }) => {
  const resetUrl = `https://accountrack.onrender.com?resetToken=${token}`;
  await transporter.sendMail({
    from: process.env.SMTP_FROM,
    to,
    subject: 'AccounTrack Password Reset Request',
    html: `
      <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;">
        <div style="background:#0a4f45;padding:24px;text-align:center;">
          <h1 style="color:white;margin:0;font-size:22px;">AccounTrack™ Pro</h1>
        </div>
        <div style="padding:32px;background:#f9f9f9;">
          <p>Hello ${firstName},</p>
          <p>You requested a password reset. Click the button below to set a new password.</p>
          <div style="text-align:center;margin:24px 0;">
            <a href="${resetUrl}" style="background:#0a4f45;color:white;padding:14px 28px;
               border-radius:8px;text-decoration:none;font-weight:bold;font-size:16px;">
              Reset My Password
            </a>
          </div>
          <p style="color:#999;font-size:13px;">This link expires in 1 hour. If you did not request this, ignore this email.</p>
        </div>
      </div>`
  });
};
