const INDUSTRIES = [
  {
    id: 'manufacturing',
    icon: 'fas fa-industry',
    name: 'Manufacturing',
    desc: 'Factory & production',
    accounts: [
      { code: '1000', name: 'Cash & Cash Equivalents', type: 'Asset', balance: 0 },
      { code: '1100', name: 'Accounts Receivable', type: 'Asset', balance: 0 },
      { code: '1200', name: 'Raw Materials Inventory', type: 'Asset', balance: 0 },
      { code: '1210', name: 'Work-in-Progress (WIP)', type: 'Asset', balance: 0 },
      { code: '1220', name: 'Finished Goods Inventory', type: 'Asset', balance: 0 },
      { code: '1300', name: 'Prepaid Expenses', type: 'Asset', balance: 0 },
      { code: '1400', name: 'Factory Equipment', type: 'Asset', balance: 0 },
      { code: '1410', name: 'Accumulated Depreciation — Equipment', type: 'Asset', balance: 0 },
      { code: '1500', name: 'Land & Buildings', type: 'Asset', balance: 0 },
      { code: '2000', name: 'Accounts Payable', type: 'Liability', balance: 0 },
      { code: '2100', name: 'VAT Payable (7.5%)', type: 'Liability', balance: 0 },
      { code: '2200', name: 'PAYE Tax Payable', type: 'Liability', balance: 0 },
      { code: '2300', name: 'Pension Payable', type: 'Liability', balance: 0 },
      { code: '2400', name: 'Bank Loans Payable', type: 'Liability', balance: 0 },
      { code: '3000', name: 'Share Capital', type: 'Equity', balance: 0 },
      { code: '3100', name: 'Retained Earnings', type: 'Equity', balance: 0 },
      { code: '3200', name: 'Drawings', type: 'Equity', balance: 0 },
      { code: '4000', name: 'Product Sales Revenue', type: 'Revenue', balance: 0 },
      { code: '4100', name: 'Export Revenue', type: 'Revenue', balance: 0 },
      { code: '5000', name: 'Cost of Goods Sold', type: 'Expense', balance: 0 },
      { code: '5100', name: 'Raw Materials Consumed', type: 'Expense', balance: 0 },
      { code: '5200', name: 'Direct Labour', type: 'Expense', balance: 0 },
      { code: '5300', name: 'Factory Overhead', type: 'Expense', balance: 0 },
      { code: '6000', name: 'Salary & Wages', type: 'Expense', balance: 0 },
      { code: '6100', name: 'Rent — Factory', type: 'Expense', balance: 0 },
      { code: '6200', name: 'Utilities — Factory', type: 'Expense', balance: 0 },
      { code: '6300', name: 'Maintenance & Repairs', type: 'Expense', balance: 0 },
      { code: '6400', name: 'Depreciation Expense', type: 'Expense', balance: 0 },
      { code: '6500', name: 'Marketing & Distribution', type: 'Expense', balance: 0 }
    ]
  },
  {
    id: 'trading',
    icon: 'fas fa-store',
    name: 'Trading / Retail',
    desc: 'Buy & sell goods',
    accounts: [
      { code: '1000', name: 'Cash & Cash Equivalents', type: 'Asset', balance: 0 },
      { code: '1100', name: 'Accounts Receivable', type: 'Asset', balance: 0 },
      { code: '1200', name: 'Merchandise Inventory', type: 'Asset', balance: 0 },
      { code: '1300', name: 'Prepaid Expenses', type: 'Asset', balance: 0 },
      { code: '1400', name: 'Store Equipment', type: 'Asset', balance: 0 },
      { code: '1410', name: 'Accumulated Depreciation', type: 'Asset', balance: 0 },
      { code: '2000', name: 'Accounts Payable', type: 'Liability', balance: 0 },
      { code: '2100', name: 'VAT Payable (7.5%)', type: 'Liability', balance: 0 },
      { code: '2200', name: 'PAYE Payable', type: 'Liability', balance: 0 },
      { code: '2300', name: 'Pension Payable', type: 'Liability', balance: 0 },
      { code: '3000', name: 'Owner Capital', type: 'Equity', balance: 0 },
      { code: '3100', name: 'Retained Earnings', type: 'Equity', balance: 0 },
      { code: '3200', name: 'Drawings', type: 'Equity', balance: 0 },
      { code: '4000', name: 'Sales Revenue', type: 'Revenue', balance: 0 },
      { code: '4100', name: 'Sales Returns & Allowances', type: 'Revenue', balance: 0 },
      { code: '5000', name: 'Cost of Goods Sold', type: 'Expense', balance: 0 },
      { code: '6000', name: 'Salaries & Wages', type: 'Expense', balance: 0 },
      { code: '6100', name: 'Rent Expense', type: 'Expense', balance: 0 },
      { code: '6200', name: 'Utilities', type: 'Expense', balance: 0 },
      { code: '6300', name: 'Advertising & Promotions', type: 'Expense', balance: 0 },
      { code: '6400', name: 'Packaging & Shipping', type: 'Expense', balance: 0 },
      { code: '6500', name: 'Inventory Write-down', type: 'Expense', balance: 0 }
    ]
  },
  {
    id: 'construction',
    icon: 'fas fa-hard-hat',
    name: 'Construction',
    desc: 'Engineering & building',
    accounts: [
      { code: '1000', name: 'Cash & Bank', type: 'Asset', balance: 0 },
      { code: '1100', name: 'Accounts Receivable', type: 'Asset', balance: 0 },
      { code: '1150', name: 'Retention Receivable', type: 'Asset', balance: 0 },
      { code: '1200', name: 'Construction Materials Inventory', type: 'Asset', balance: 0 },
      { code: '1300', name: 'Prepaid Insurance', type: 'Asset', balance: 0 },
      { code: '1400', name: 'Plant & Heavy Equipment', type: 'Asset', balance: 0 },
      { code: '1410', name: 'Accumulated Depreciation', type: 'Asset', balance: 0 },
      { code: '2000', name: 'Accounts Payable', type: 'Liability', balance: 0 },
      { code: '2050', name: 'Retention Payable (Subcontractors)', type: 'Liability', balance: 0 },
      { code: '2100', name: 'VAT Payable', type: 'Liability', balance: 0 },
      { code: '2200', name: 'PAYE Payable', type: 'Liability', balance: 0 },
      { code: '2300', name: 'Pension Payable', type: 'Liability', balance: 0 },
      { code: '2400', name: 'Bank Loan Payable', type: 'Liability', balance: 0 },
      { code: '3000', name: 'Share Capital', type: 'Equity', balance: 0 },
      { code: '3100', name: 'Retained Earnings', type: 'Equity', balance: 0 },
      { code: '3200', name: 'Drawings', type: 'Equity', balance: 0 },
      { code: '4000', name: 'Contract Revenue', type: 'Revenue', balance: 0 },
      { code: '4100', name: 'Variation Orders Revenue', type: 'Revenue', balance: 0 },
      { code: '5000', name: 'Direct Materials Cost', type: 'Expense', balance: 0 },
      { code: '5100', name: 'Direct Labour Cost', type: 'Expense', balance: 0 },
      { code: '5200', name: 'Subcontractor Costs', type: 'Expense', balance: 0 },
      { code: '5300', name: 'Equipment Hire / Plant', type: 'Expense', balance: 0 },
      { code: '6000', name: 'Site Salaries', type: 'Expense', balance: 0 },
      { code: '6100', name: 'Project Management Costs', type: 'Expense', balance: 0 },
      { code: '6200', name: 'Depreciation — Plant', type: 'Expense', balance: 0 },
      { code: '6300', name: 'Insurance Expense', type: 'Expense', balance: 0 },
      { code: '6400', name: 'Site Utilities & Overheads', type: 'Expense', balance: 0 }
    ]
  },
  {
    id: 'healthcare',
    icon: 'fas fa-hospital',
    name: 'Healthcare',
    desc: 'Hospitals & clinics',
    accounts: [
      { code: '1000', name: 'Cash & Bank', type: 'Asset', balance: 0 },
      { code: '1100', name: 'Patient Receivables', type: 'Asset', balance: 0 },
      { code: '1110', name: 'HMO/Insurance Receivables', type: 'Asset', balance: 0 },
      { code: '1200', name: 'Pharmaceutical Inventory', type: 'Asset', balance: 0 },
      { code: '1210', name: 'Medical Supplies Inventory', type: 'Asset', balance: 0 },
      { code: '1300', name: 'Prepaid Expenses', type: 'Asset', balance: 0 },
      { code: '1400', name: 'Medical Equipment', type: 'Asset', balance: 0 },
      { code: '1410', name: 'Accumulated Depreciation', type: 'Asset', balance: 0 },
      { code: '2000', name: 'Accounts Payable', type: 'Liability', balance: 0 },
      { code: '2100', name: 'VAT Payable', type: 'Liability', balance: 0 },
      { code: '2200', name: 'PAYE Payable', type: 'Liability', balance: 0 },
      { code: '2300', name: 'Pension Payable', type: 'Liability', balance: 0 },
      { code: '3000', name: 'Share Capital', type: 'Equity', balance: 0 },
      { code: '3100', name: 'Retained Earnings', type: 'Equity', balance: 0 },
      { code: '3200', name: 'Drawings', type: 'Equity', balance: 0 },
      { code: '4000', name: 'Consultation Fees', type: 'Revenue', balance: 0 },
      { code: '4100', name: 'Surgical Procedures Revenue', type: 'Revenue', balance: 0 },
      { code: '4200', name: 'Laboratory & Diagnostics Revenue', type: 'Revenue', balance: 0 },
      { code: '4300', name: 'Pharmacy Sales', type: 'Revenue', balance: 0 },
      { code: '4400', name: 'HMO Claims Revenue', type: 'Revenue', balance: 0 },
      { code: '5000', name: 'Cost of Pharmaceutical Goods', type: 'Expense', balance: 0 },
      { code: '5100', name: 'Medical Supplies Used', type: 'Expense', balance: 0 },
      { code: '6000', name: 'Medical Staff Salaries', type: 'Expense', balance: 0 },
      { code: '6100', name: 'Rent — Facility', type: 'Expense', balance: 0 },
      { code: '6200', name: 'Utilities', type: 'Expense', balance: 0 },
      { code: '6300', name: 'Equipment Maintenance', type: 'Expense', balance: 0 },
      { code: '6400', name: 'Regulatory & License Fees', type: 'Expense', balance: 0 }
    ]
  },
  {
    id: 'hospitality',
    icon: 'fas fa-hotel',
    name: 'Hospitality',
    desc: 'Hotels & restaurants',
    accounts: [
      { code: '1000', name: 'Cash & Bank', type: 'Asset', balance: 0 },
      { code: '1100', name: 'Accounts Receivable', type: 'Asset', balance: 0 },
      { code: '1200', name: 'Food & Beverage Inventory', type: 'Asset', balance: 0 },
      { code: '1210', name: 'Operating Supplies Inventory', type: 'Asset', balance: 0 },
      { code: '1300', name: 'Prepaid Insurance', type: 'Asset', balance: 0 },
      { code: '1400', name: 'Furniture, Fittings & Equipment', type: 'Asset', balance: 0 },
      { code: '1410', name: 'Accumulated Depreciation', type: 'Asset', balance: 0 },
      { code: '1500', name: 'Land & Building', type: 'Asset', balance: 0 },
      { code: '2000', name: 'Accounts Payable', type: 'Liability', balance: 0 },
      { code: '2100', name: 'VAT Payable', type: 'Liability', balance: 0 },
      { code: '2200', name: 'PAYE Payable', type: 'Liability', balance: 0 },
      { code: '2300', name: 'Pension Payable', type: 'Liability', balance: 0 },
      { code: '2400', name: 'Guest Deposits', type: 'Liability', balance: 0 },
      { code: '3000', name: 'Share Capital', type: 'Equity', balance: 0 },
      { code: '3100', name: 'Retained Earnings', type: 'Equity', balance: 0 },
      { code: '3200', name: 'Drawings', type: 'Equity', balance: 0 },
      { code: '4000', name: 'Room Revenue', type: 'Revenue', balance: 0 },
      { code: '4100', name: 'Food & Beverage Revenue', type: 'Revenue', balance: 0 },
      { code: '4200', name: 'Event / Conference Revenue', type: 'Revenue', balance: 0 },
      { code: '4300', name: 'Spa & Leisure Revenue', type: 'Revenue', balance: 0 },
      { code: '5000', name: 'Cost of Food & Beverage', type: 'Expense', balance: 0 },
      { code: '6000', name: 'Salaries & Service Charge', type: 'Expense', balance: 0 },
      { code: '6100', name: 'Rent Expense', type: 'Expense', balance: 0 },
      { code: '6200', name: 'Utilities — Electricity & Water', type: 'Expense', balance: 0 },
      { code: '6300', name: 'Linen & Housekeeping Supplies', type: 'Expense', balance: 0 },
      { code: '6400', name: 'Marketing & Advertising', type: 'Expense', balance: 0 },
      { code: '6500', name: 'Repairs & Maintenance', type: 'Expense', balance: 0 }
    ]
  },
  {
    id: 'education',
    icon: 'fas fa-graduation-cap',
    name: 'Education',
    desc: 'Schools & academies',
    accounts: [
      { code: '1000', name: 'Cash & Bank', type: 'Asset', balance: 0 },
      { code: '1100', name: 'Tuition Fees Receivable', type: 'Asset', balance: 0 },
      { code: '1200', name: 'Books & Educational Materials', type: 'Asset', balance: 0 },
      { code: '1300', name: 'Prepaid Expenses', type: 'Asset', balance: 0 },
      { code: '1400', name: 'Furniture & Equipment', type: 'Asset', balance: 0 },
      { code: '1410', name: 'Accumulated Depreciation', type: 'Asset', balance: 0 },
      { code: '1500', name: 'Land & Building', type: 'Asset', balance: 0 },
      { code: '2000', name: 'Accounts Payable', type: 'Liability', balance: 0 },
      { code: '2100', name: 'VAT Payable', type: 'Liability', balance: 0 },
      { code: '2200', name: 'PAYE Payable', type: 'Liability', balance: 0 },
      { code: '2300', name: 'Pension Payable', type: 'Liability', balance: 0 },
      { code: '2400', name: 'Deferred Tuition Revenue', type: 'Liability', balance: 0 },
      { code: '3000', name: 'Endowment Fund', type: 'Equity', balance: 0 },
      { code: '3100', name: 'Retained Surplus', type: 'Equity', balance: 0 },
      { code: '4000', name: 'Tuition Fees Revenue', type: 'Revenue', balance: 0 },
      { code: '4100', name: 'Boarding Fees Revenue', type: 'Revenue', balance: 0 },
      { code: '4200', name: 'Examination Fees', type: 'Revenue', balance: 0 },
      { code: '4300', name: 'Grants & Donations', type: 'Revenue', balance: 0 },
      { code: '5000', name: 'Academic Staff Salaries', type: 'Expense', balance: 0 },
      { code: '6000', name: 'Administrative Salaries', type: 'Expense', balance: 0 },
      { code: '6100', name: 'Rent & Facility', type: 'Expense', balance: 0 },
      { code: '6200', name: 'Utilities', type: 'Expense', balance: 0 },
      { code: '6300', name: 'Books & Stationery', type: 'Expense', balance: 0 },
      { code: '6400', name: 'Examination Costs', type: 'Expense', balance: 0 },
      { code: '6500', name: 'Sports & Extra-Curricular', type: 'Expense', balance: 0 }
    ]
  },
  {
    id: 'fintech',
    icon: 'fas fa-money-bill-transfer',
    name: 'Financial Services',
    desc: 'Banks, MFBs & fintech',
    accounts: [
      { code: '1000', name: 'Cash & Vault', type: 'Asset', balance: 0 },
      { code: '1050', name: 'Central Bank Reserve', type: 'Asset', balance: 0 },
      { code: '1100', name: 'Loans Receivable', type: 'Asset', balance: 0 },
      { code: '1110', name: 'Interest Receivable', type: 'Asset', balance: 0 },
      { code: '1200', name: 'Investment Securities', type: 'Asset', balance: 0 },
      { code: '1300', name: 'Prepaid Expenses', type: 'Asset', balance: 0 },
      { code: '1400', name: 'Property & Equipment', type: 'Asset', balance: 0 },
      { code: '1410', name: 'Accumulated Depreciation', type: 'Asset', balance: 0 },
      { code: '2000', name: 'Customer Deposits', type: 'Liability', balance: 0 },
      { code: '2100', name: 'Borrowings', type: 'Liability', balance: 0 },
      { code: '2200', name: 'PAYE Payable', type: 'Liability', balance: 0 },
      { code: '2300', name: 'Pension Payable', type: 'Liability', balance: 0 },
      { code: '2400', name: 'Deferred Income', type: 'Liability', balance: 0 },
      { code: '3000', name: 'Share Capital', type: 'Equity', balance: 0 },
      { code: '3100', name: 'Retained Earnings', type: 'Equity', balance: 0 },
      { code: '3200', name: 'Drawings', type: 'Equity', balance: 0 },
      { code: '3300', name: 'Regulatory Reserves', type: 'Equity', balance: 0 },
      { code: '4000', name: 'Interest Income on Loans', type: 'Revenue', balance: 0 },
      { code: '4100', name: 'Fee & Commission Income', type: 'Revenue', balance: 0 },
      { code: '4200', name: 'Foreign Exchange Income', type: 'Revenue', balance: 0 },
      { code: '4300', name: 'Investment Income', type: 'Revenue', balance: 0 },
      { code: '5000', name: 'Interest Expense on Deposits', type: 'Expense', balance: 0 },
      { code: '5100', name: 'Loan Loss Provisions', type: 'Expense', balance: 0 },
      { code: '6000', name: 'Salaries & Benefits', type: 'Expense', balance: 0 },
      { code: '6100', name: 'Rent & Premises', type: 'Expense', balance: 0 },
      { code: '6200', name: 'Technology & IT', type: 'Expense', balance: 0 },
      { code: '6300', name: 'Regulatory Fees', type: 'Expense', balance: 0 },
      { code: '6400', name: 'Marketing & Advertising', type: 'Expense', balance: 0 }
    ]
  },
  {
    id: 'agriculture',
    icon: 'fas fa-seedling',
    name: 'Agriculture',
    desc: 'Farming & agribusiness',
    accounts: [
      { code: '1000', name: 'Cash & Bank', type: 'Asset', balance: 0 },
      { code: '1100', name: 'Accounts Receivable', type: 'Asset', balance: 0 },
      { code: '1200', name: 'Crop Inventory', type: 'Asset', balance: 0 },
      { code: '1210', name: 'Livestock Assets', type: 'Asset', balance: 0 },
      { code: '1220', name: 'Agrochemicals & Seeds', type: 'Asset', balance: 0 },
      { code: '1300', name: 'Prepaid Farm Insurance', type: 'Asset', balance: 0 },
      { code: '1400', name: 'Farm Equipment & Machinery', type: 'Asset', balance: 0 },
      { code: '1410', name: 'Accumulated Depreciation', type: 'Asset', balance: 0 },
      { code: '1500', name: 'Land', type: 'Asset', balance: 0 },
      { code: '2000', name: 'Accounts Payable', type: 'Liability', balance: 0 },
      { code: '2100', name: 'VAT Payable', type: 'Liability', balance: 0 },
      { code: '2200', name: 'PAYE Payable', type: 'Liability', balance: 0 },
      { code: '2300', name: 'Pension Payable', type: 'Liability', balance: 0 },
      { code: '2400', name: 'Agricultural Loans', type: 'Liability', balance: 0 },
      { code: '3000', name: 'Owner Capital', type: 'Equity', balance: 0 },
      { code: '3100', name: 'Retained Earnings', type: 'Equity', balance: 0 },
      { code: '3200', name: 'Drawings', type: 'Equity', balance: 0 },
      { code: '4000', name: 'Crop Sales Revenue', type: 'Revenue', balance: 0 },
      { code: '4100', name: 'Livestock Sales Revenue', type: 'Revenue', balance: 0 },
      { code: '4200', name: 'Government Grants / Subsidies', type: 'Revenue', balance: 0 },
      { code: '5000', name: 'Seeds & Planting Materials', type: 'Expense', balance: 0 },
      { code: '5100', name: 'Fertilizers & Chemicals', type: 'Expense', balance: 0 },
      { code: '5200', name: 'Harvesting & Processing Costs', type: 'Expense', balance: 0 },
      { code: '6000', name: 'Farm Labour', type: 'Expense', balance: 0 },
      { code: '6100', name: 'Fuel & Transportation', type: 'Expense', balance: 0 },
      { code: '6200', name: 'Equipment Maintenance', type: 'Expense', balance: 0 },
      { code: '6300', name: 'Land Lease', type: 'Expense', balance: 0 },
      { code: '6400', name: 'Insurance', type: 'Expense', balance: 0 }
    ]
  },
  {
    id: 'tech',
    icon: 'fas fa-laptop-code',
    name: 'Technology / ICT',
    desc: 'Software & IT services',
    accounts: [
      { code: '1000', name: 'Cash & Bank', type: 'Asset', balance: 0 },
      { code: '1100', name: 'Accounts Receivable', type: 'Asset', balance: 0 },
      { code: '1110', name: 'Unbilled Revenue', type: 'Asset', balance: 0 },
      { code: '1200', name: 'Software Licenses Inventory', type: 'Asset', balance: 0 },
      { code: '1300', name: 'Prepaid SaaS & Subscriptions', type: 'Asset', balance: 0 },
      { code: '1400', name: 'Computer Hardware', type: 'Asset', balance: 0 },
      { code: '1410', name: 'Accumulated Depreciation', type: 'Asset', balance: 0 },
      { code: '1500', name: 'Intangible Assets — Software', type: 'Asset', balance: 0 },
      { code: '2000', name: 'Accounts Payable', type: 'Liability', balance: 0 },
      { code: '2100', name: 'VAT Payable', type: 'Liability', balance: 0 },
      { code: '2200', name: 'PAYE Payable', type: 'Liability', balance: 0 },
      { code: '2300', name: 'Pension Payable', type: 'Liability', balance: 0 },
      { code: '2400', name: 'Deferred Revenue', type: 'Liability', balance: 0 },
      { code: '3000', name: 'Share Capital', type: 'Equity', balance: 0 },
      { code: '3100', name: 'Retained Earnings', type: 'Equity', balance: 0 },
      { code: '3200', name: 'Drawings', type: 'Equity', balance: 0 },
      { code: '4000', name: 'Software Sales Revenue', type: 'Revenue', balance: 0 },
      { code: '4100', name: 'SaaS Subscription Revenue', type: 'Revenue', balance: 0 },
      { code: '4200', name: 'IT Consulting Revenue', type: 'Revenue', balance: 0 },
      { code: '4300', name: 'Support & Maintenance Revenue', type: 'Revenue', balance: 0 },
      { code: '5000', name: 'Cost of Software Development', type: 'Expense', balance: 0 },
      { code: '5100', name: 'Third-party Licenses', type: 'Expense', balance: 0 },
      { code: '6000', name: 'Engineering Salaries', type: 'Expense', balance: 0 },
      { code: '6100', name: 'Office Rent', type: 'Expense', balance: 0 },
      { code: '6200', name: 'Cloud Infrastructure (AWS/Azure)', type: 'Expense', balance: 0 },
      { code: '6300', name: 'Research & Development', type: 'Expense', balance: 0 },
      { code: '6400', name: 'Marketing & Customer Acquisition', type: 'Expense', balance: 0 },
      { code: '6500', name: 'Legal & Compliance', type: 'Expense', balance: 0 }
    ]
  },
  {
    id: 'oil',
    icon: 'fas fa-oil-well',
    name: 'Oil & Gas / Energy',
    desc: 'Upstream, midstream, downstream',
    accounts: [
      { code: '1000', name: 'Cash & Bank', type: 'Asset', balance: 0 },
      { code: '1100', name: 'Trade Receivables', type: 'Asset', balance: 0 },
      { code: '1200', name: 'Crude Oil Inventory', type: 'Asset', balance: 0 },
      { code: '1210', name: 'Refined Products Inventory', type: 'Asset', balance: 0 },
      { code: '1300', name: 'Prepaid Expenses', type: 'Asset', balance: 0 },
      { code: '1400', name: 'Drilling Equipment', type: 'Asset', balance: 0 },
      { code: '1410', name: 'Accumulated Depletion & Depreciation', type: 'Asset', balance: 0 },
      { code: '1500', name: 'Oil & Gas Properties (E&P)', type: 'Asset', balance: 0 },
      { code: '2000', name: 'Trade Payables', type: 'Liability', balance: 0 },
      { code: '2100', name: 'VAT Payable', type: 'Liability', balance: 0 },
      { code: '2200', name: 'PAYE Payable', type: 'Liability', balance: 0 },
      { code: '2300', name: 'Pension Payable', type: 'Liability', balance: 0 },
      { code: '2400', name: 'DPR / NUPRC Levies Payable', type: 'Liability', balance: 0 },
      { code: '2500', name: 'Long-term Debt', type: 'Liability', balance: 0 },
      { code: '3000', name: 'Share Capital', type: 'Equity', balance: 0 },
      { code: '3100', name: 'Retained Earnings', type: 'Equity', balance: 0 },
      { code: '3200', name: 'Drawings', type: 'Equity', balance: 0 },
      { code: '4000', name: 'Crude Oil Sales', type: 'Revenue', balance: 0 },
      { code: '4100', name: 'Refined Products Sales', type: 'Revenue', balance: 0 },
      { code: '4200', name: 'Gas Sales Revenue', type: 'Revenue', balance: 0 },
      { code: '5000', name: 'Lifting Costs', type: 'Expense', balance: 0 },
      { code: '5100', name: 'Royalties Expense', type: 'Expense', balance: 0 },
      { code: '5200', name: 'Depletion, Depreciation & Amortisation', type: 'Expense', balance: 0 },
      { code: '6000', name: 'Employee Costs', type: 'Expense', balance: 0 },
      { code: '6100', name: 'Exploration Costs (Dry Holes)', type: 'Expense', balance: 0 },
      { code: '6200', name: 'Environmental & Remediation', type: 'Expense', balance: 0 },
      { code: '6300', name: 'Transportation & Pipeline', type: 'Expense', balance: 0 },
      { code: '6400', name: 'Government Levies & Taxes', type: 'Expense', balance: 0 }
    ]
  },
  {
    id: 'ngo',
    icon: 'fas fa-hands-holding-heart',
    name: 'NGO / Non-Profit',
    desc: 'Foundations & charities',
    accounts: [
      { code: '1000', name: 'Cash & Bank', type: 'Asset', balance: 0 },
      { code: '1100', name: 'Grants Receivable', type: 'Asset', balance: 0 },
      { code: '1200', name: 'Programme Supplies', type: 'Asset', balance: 0 },
      { code: '1300', name: 'Prepaid Expenses', type: 'Asset', balance: 0 },
      { code: '1400', name: 'Equipment & Furniture', type: 'Asset', balance: 0 },
      { code: '1410', name: 'Accumulated Depreciation', type: 'Asset', balance: 0 },
      { code: '2000', name: 'Accounts Payable', type: 'Liability', balance: 0 },
      { code: '2200', name: 'PAYE Payable', type: 'Liability', balance: 0 },
      { code: '2300', name: 'Pension Payable', type: 'Liability', balance: 0 },
      { code: '2400', name: 'Deferred Grant Income', type: 'Liability', balance: 0 },
      { code: '3000', name: 'Unrestricted Fund Balance', type: 'Equity', balance: 0 },
      { code: '3100', name: 'Restricted Fund Balance', type: 'Equity', balance: 0 },
      { code: '4000', name: 'Donor Grants — Unrestricted', type: 'Revenue', balance: 0 },
      { code: '4100', name: 'Donor Grants — Restricted', type: 'Revenue', balance: 0 },
      { code: '4200', name: 'Membership Dues', type: 'Revenue', balance: 0 },
      { code: '4300', name: 'Programme Revenue', type: 'Revenue', balance: 0 },
      { code: '5000', name: 'Programme Expenses', type: 'Expense', balance: 0 },
      { code: '6000', name: 'Staff Salaries', type: 'Expense', balance: 0 },
      { code: '6100', name: 'Rent & Facility', type: 'Expense', balance: 0 },
      { code: '6200', name: 'Travel & Field Operations', type: 'Expense', balance: 0 },
      { code: '6300', name: 'Monitoring & Evaluation', type: 'Expense', balance: 0 },
      { code: '6400', name: 'Communication & Reporting', type: 'Expense', balance: 0 },
      { code: '6500', name: 'Overhead & Administration', type: 'Expense', balance: 0 }
    ]
  },
  {
    id: 'realestate',
    icon: 'fas fa-building-columns',
    name: 'Real Estate',
    desc: 'Property & development',
    accounts: [
      { code: '1000', name: 'Cash & Bank', type: 'Asset', balance: 0 },
      { code: '1100', name: 'Rent Receivable', type: 'Asset', balance: 0 },
      { code: '1200', name: 'Properties Held for Sale', type: 'Asset', balance: 0 },
      { code: '1210', name: 'Investment Properties', type: 'Asset', balance: 0 },
      { code: '1300', name: 'Prepaid Expenses', type: 'Asset', balance: 0 },
      { code: '1400', name: 'Office Equipment', type: 'Asset', balance: 0 },
      { code: '2000', name: 'Accounts Payable', type: 'Liability', balance: 0 },
      { code: '2100', name: 'VAT Payable', type: 'Liability', balance: 0 },
      { code: '2200', name: 'PAYE Payable', type: 'Liability', balance: 0 },
      { code: '2300', name: 'Pension Payable', type: 'Liability', balance: 0 },
      { code: '2400', name: 'Mortgage / Bond Payable', type: 'Liability', balance: 0 },
      { code: '2500', name: 'Tenant Deposits', type: 'Liability', balance: 0 },
      { code: '3000', name: 'Share Capital', type: 'Equity', balance: 0 },
      { code: '3100', name: 'Retained Earnings', type: 'Equity', balance: 0 },
      { code: '3200', name: 'Drawings', type: 'Equity', balance: 0 },
      { code: '4000', name: 'Rental Income', type: 'Revenue', balance: 0 },
      { code: '4100', name: 'Property Sales Revenue', type: 'Revenue', balance: 0 },
      { code: '4200', name: 'Property Management Fees', type: 'Revenue', balance: 0 },
      { code: '5000', name: 'Cost of Properties Sold', type: 'Expense', balance: 0 },
      { code: '5100', name: 'Development Costs', type: 'Expense', balance: 0 },
      { code: '6000', name: 'Staff Salaries', type: 'Expense', balance: 0 },
      { code: '6100', name: 'Property Maintenance', type: 'Expense', balance: 0 },
      { code: '6200', name: 'Insurance', type: 'Expense', balance: 0 },
      { code: '6300', name: 'Legal & Agency Fees', type: 'Expense', balance: 0 },
      { code: '6400', name: 'Marketing', type: 'Expense', balance: 0 },
      { code: '6500', name: 'Property Taxes & Levies', type: 'Expense', balance: 0 }
    ]
  }
];

module.exports = INDUSTRIES;